name: amplify_logging_dart
description: Dart implementation of the Amplify Logging plugin
version: 0.1.0
homepage: https://docs.amplify.aws/lib/q/platform/flutter/
repository: https://github.com/aws-amplify/amplify-flutter/tree/next/packages/logging/amplify_logging_dart
issue_tracker: https://github.com/aws-amplify/amplify-flutter/issues

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  amplify_core: ">=1.0.0-next.1 <1.0.0-next.2"
  aws_common: ">=0.3.0 <0.4.0"
  aws_signature_v4: ">=0.3.0 <0.4.0"
  built_collection: ^5.0.0
  built_value: ">=8.4.0 <8.5.0"
  fixnum: ^1.0.0
  meta: ^1.7.0
  smithy: ">=0.3.0 <0.4.0"
  smithy_aws: ">=0.3.0 <0.4.0"

dev_dependencies:
  amplify_lints: ^2.0.0
  build_runner: ^2.0.0
  built_value_generator: 8.4.2
  test: ^1.16.0
