name: amplify_logging
description: A logging plugin for Amplify projects.
version: 0.1.0
homepage: https://docs.amplify.aws/lib/q/platform/flutter/
repository: https://github.com/aws-amplify/amplify-flutter/tree/next/packages/logging/amplify_logging
issue_tracker: https://github.com/aws-amplify/amplify-flutter/issues

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ">=3.0.0"

dependencies:
  amplify_flutter: ">=1.0.0-next.1 <1.0.0-next.2"
  amplify_logging_dart: ">=0.1.0 <0.2.0"
  flutter:
    sdk: flutter

dev_dependencies:
  amplify_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.amazonaws.amplify.amplify_logging
        pluginClass: AmplifyLoggingPlugin
      ios:
        pluginClass: AmplifyLoggingPlugin
